"""add estate model

Revision ID: 3a0c8efd80bb
Revises: 4420db232097
Create Date: 2020-08-11 17:28:27.560345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0c8efd80bb'
down_revision = '4420db232097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=False),
    sa.Column('characteristics', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.Enum('Apartment', 'House'), nullable=False),
    sa.Column('finality', sa.Enum('Residencial', 'Office'), nullable=True),
    sa.Column('estate_agency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estate_agency_id'], ['estate_agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estate')
    # ### end Alembic commands ###
